language: python

cache: pip

install:
    - pip install --no-cache-dir -r requirements.txt
    - pip install tox tox-venv tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov

notifications:
    email: false
